(() => {
  const $ = (selector) => document.querySelector(selector);
  const rows = [
    { grade:'ม.2 / 1', number:'10002', name:'เด็กหญิงมาลี รักเรียน', level:'ตรี', certificate:'TR-2568-001', status:'ยังไม่รับ' },
    { grade:'ม.4 / 2', number:'40001', name:'นายวิทยา ตั้งใจ', level:'ตรี', certificate:'TR-2567-009', status:'ยังไม่รับ' },
  ];
  let filtered = rows.slice();
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]));
  const render = () => { $('#pickup-count').textContent = `พบ ${filtered.length.toLocaleString('th-TH')} รายการ`; $('#pickup-body').innerHTML = filtered.map((row, index) => `<tr data-row="${index}"><td>${esc(row.grade)}</td><td>${esc(row.number)}</td><td>${esc(row.name)}</td><td>ธรรมศึกษาชั้น${esc(row.level)}</td><td>${esc(row.certificate)}</td><td>${esc(row.status)}</td><td><button data-claim="${index}" type="button">บันทึกรับแล้ว</button></td></tr>`).join(''); document.querySelectorAll('[data-claim]').forEach((button) => button.addEventListener('click', () => { const row = filtered[Number(button.dataset.claim)]; row.status = 'รับแล้ว'; render(); })); };
  const csv = () => { const body = [['ชั้น/ห้อง','เลขประจำตัว','ชื่อ-นามสกุล','ระดับ','เลขใบประกาศ','สถานะ'], ...filtered.map((row) => [row.grade,row.number,row.name,row.level,row.certificate,row.status])]; const text = '\ufeff' + body.map((line) => line.map((value) => `"${String(value).replace(/"/g,'""')}"`).join(',')).join('\r\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([text], { type:'text/csv;charset=utf-8' })); link.download = 'certificate-pickup-2569.csv'; link.click(); };
  $('#pin-form').addEventListener('submit', (event) => { event.preventDefault(); if ($('#pin').value !== '1234') { $('#pin-message').textContent = 'รหัสไม่ถูกต้อง'; $('#pin-message').classList.add('error'); return; } $('#login-card').classList.add('admin-hidden'); $('#admin-workspace').classList.remove('admin-hidden'); render(); });
  $('#admin-search').addEventListener('input', (event) => { const query = event.target.value.trim().toLocaleLowerCase('th-TH'); filtered = rows.filter((row) => Object.values(row).some((value) => String(value).toLocaleLowerCase('th-TH').includes(query))); render(); }); $('#export-csv').addEventListener('click', csv); $('#print').addEventListener('click', () => window.print()); $('#font-upload').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = (loadEvent) => { const style = document.createElement('style'); style.textContent = `@font-face{font-family:AdminUploaded;src:url(${loadEvent.target.result})}body{font-family:AdminUploaded,sans-serif}`; document.head.appendChild(style); }; reader.readAsDataURL(file); });
})();
